"""
MAVLink message encoder/decoder using pymavlink-generated mavlink.py.

Uses the mavlink.py module generated by pymavlink.tools.mavgen for
encoding and decoding MAVLink messages.
"""

import re
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any

from .codec import Signal, Message, DeviceConfig

try:
    from . import mavlink
except ImportError:
    mavlink = None


def encode_mavlink(msg_name: str, values: dict[str, Any], sys_id: int = 1, comp_id: int = 1) -> bytes:
    """
    Encode a MAVLink message using pymavlink.

    Args:
        msg_name: Message name (e.g., "ARM_MODE_SWITCH")
        values: Dict of field_name -> value
        sys_id: System ID
        comp_id: Component ID

    Returns:
        Complete MAVLink v2 frame bytes
    """
    if mavlink is None:
        raise ImportError("mavlink.py not found. Generate it using pymavlink.tools.mavgen")

    # Create MAVLink instance
    mav = mavlink.MAVLink(None, srcSystem=sys_id, srcComponent=comp_id)

    # Get message class
    msg_class_name = f"MAVLink_{msg_name.lower()}_message"
    msg_class = getattr(mavlink, msg_class_name, None)
    if msg_class is None:
        raise ValueError(f"Unknown message: {msg_name}")

    # Expand array syntax: position=[1,2,3] -> position_0=1, position_1=2, position_2=3
    expanded_values = {}
    for key, val in values.items():
        if isinstance(val, (list, tuple)):
            for i, item in enumerate(val):
                expanded_values[f"{key}_{i}"] = item
        else:
            expanded_values[key] = val

    # Get field names and build args
    fieldnames = msg_class.fieldnames
    args = []
    for fname in fieldnames:
        if fname in expanded_values:
            args.append(expanded_values[fname])
        else:
            # Use default value (0 for numbers)
            args.append(0)

    # Create message instance
    msg = msg_class(*args)

    # Pack to bytes
    return msg.pack(mav)


def decode_mavlink(data: bytes) -> dict[str, Any] | None:
    """
    Decode a MAVLink v2 frame.

    Args:
        data: MAVLink v2 frame bytes (starting with 0xFD)

    Returns:
        Dict with message info and field values, or None if invalid
    """
    if mavlink is None:
        raise ImportError("mavlink.py not found. Generate it using pymavlink.tools.mavgen")

    if not data or data[0] != 0xFD:
        return None

    # Create MAVLink instance with a BytesIO wrapper
    import io
    mav = mavlink.MAVLink(io.BytesIO())

    # Parse message
    try:
        msg = mav.parse_char(data)
        if msg is None:
            return None

        # Extract fields
        result = {
            "msg_name": msg.get_type(),
            "msg_id": msg.get_msgId(),
        }

        for fname in msg._fieldnames:
            result[fname] = getattr(msg, fname)

        return result
    except Exception as e:
        return None


# Keep XML loader for backward compatibility
MAVLINK_TYPES = {
    "uint8_t": (8, "unsigned"),
    "int8_t": (8, "signed"),
    "uint16_t": (16, "unsigned"),
    "int16_t": (16, "signed"),
    "uint32_t": (32, "unsigned"),
    "int32_t": (32, "signed"),
    "uint64_t": (64, "unsigned"),
    "int64_t": (64, "signed"),
    "float": (32, "float32"),
    "double": (64, "float64"),
    "char": (8, "unsigned"),
}


def _parse_type(type_str: str) -> tuple[int, str, int]:
    array_match = re.match(r"(\w+)\[(\d+)\]", type_str)
    if array_match:
        base_type = array_match.group(1)
        array_count = int(array_match.group(2))
    else:
        base_type = type_str
        array_count = 1

    if base_type not in MAVLINK_TYPES:
        raise ValueError(f"Unknown MAVLink type: {base_type}")

    bit_length, value_type = MAVLINK_TYPES[base_type]
    return bit_length, value_type, array_count


def _parse_enums(root: ET.Element) -> dict[str, dict[int, str]]:
    enums = {}
    enums_elem = root.find("enums")
    if enums_elem is None:
        return enums

    for enum_elem in enums_elem.findall("enum"):
        enum_name = enum_elem.get("name")
        if not enum_name:
            continue

        values = {}
        for entry in enum_elem.findall("entry"):
            value = entry.get("value")
            name = entry.get("name")
            if value is not None and name:
                short_name = name
                if short_name.startswith(enum_name + "_"):
                    short_name = short_name[len(enum_name) + 1:]
                values[int(value)] = short_name.lower()

        enums[enum_name] = values

    return enums


def _parse_messages(root: ET.Element, enums: dict[str, dict[int, str]]) -> list[Message]:
    messages = []
    messages_elem = root.find("messages")
    if messages_elem is None:
        return messages

    for msg_elem in messages_elem.findall("message"):
        msg_id = msg_elem.get("id")
        msg_name = msg_elem.get("name")
        if not msg_id or not msg_name:
            continue

        msg_id = int(msg_id)
        description = ""
        desc_elem = msg_elem.find("description")
        if desc_elem is not None and desc_elem.text:
            description = desc_elem.text.strip()

        signals = []
        bit_offset = 0

        for field_elem in msg_elem.findall("field"):
            field_type = field_elem.get("type")
            field_name = field_elem.get("name")
            field_enum = field_elem.get("enum")
            field_desc = field_elem.text.strip() if field_elem.text else ""

            if not field_type or not field_name:
                continue

            try:
                bit_length, value_type, array_count = _parse_type(field_type)
            except ValueError:
                continue

            enum_map = {}
            if field_enum and field_enum in enums:
                enum_map = enums[field_enum]

            if array_count > 1:
                for i in range(array_count):
                    sig = Signal(
                        name=f"{field_name}_{i}",
                        start_bit=bit_offset,
                        bit_length=bit_length,
                        byte_order="little_endian",
                        value_type=value_type,
                        description=f"{field_desc} [index {i}]" if field_desc else f"[index {i}]",
                        enum_map=enum_map.copy() if enum_map else {},
                    )
                    signals.append(sig)
                    bit_offset += bit_length
            else:
                sig = Signal(
                    name=field_name,
                    start_bit=bit_offset,
                    bit_length=bit_length,
                    byte_order="little_endian",
                    value_type=value_type,
                    description=field_desc,
                    enum_map=enum_map,
                )
                signals.append(sig)
                bit_offset += bit_length

        dlc = (bit_offset + 7) // 8

        msg = Message(
            id=msg_id,
            name=msg_name,
            direction="tx",
            dlc=dlc,
            description=description,
            signals=signals,
        )
        messages.append(msg)

    return messages


def load_mavlink_xml(path: str | Path) -> DeviceConfig:
    path = Path(path)
    tree = ET.parse(path)
    root = tree.getroot()

    enums = _parse_enums(root)
    messages = _parse_messages(root, enums)

    version = ""
    version_elem = root.find("version")
    if version_elem is not None and version_elem.text:
        version = version_elem.text.strip()

    config = DeviceConfig(
        name=path.stem,
        version=f"MAVLink v{version}" if version else "MAVLink",
        description=f"MAVLink messages from {path.name}",
        fd=True,
        messages=messages,
    )
    config.build_lookups()

    return config
