"""Generate the downloadable bridge from the canonical stdlib server implementation."""
from pathlib import Path
import hashlib
import json

root = Path(__file__).resolve().parents[1]
source = '#!/usr/bin/env python3\n' + (root / 'canfd_codec/serve.py').read_text()
source += '''
if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="CAN bridge and common simulator relay")
    parser.add_argument("--bus", default="vcan0")
    parser.add_argument("--interface", default="socketcan")
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument("--no-fd", action="store_true")
    parser.add_argument("--bitrate", type=int)
    parser.add_argument("--data-bitrate", type=int)
    parser.add_argument("--filter")
    parser.add_argument("--source")
    args = parser.parse_args()
    asyncio.run(CANWebSocketServer(bus=args.bus, interface=args.interface,
        host=args.host, port=args.port, fd=not args.no_fd, bitrate=args.bitrate,
        data_bitrate=args.data_bitrate, source_url=args.source,
        filter_ids={int(x, 0) for x in args.filter.split(",")} if args.filter else None).run())
'''
target = root / 'web/src/lib/server-script.ts'
target.write_text('// Generated by scripts/generate_bridge.py. Do not edit by hand.\n'
    + 'export const SERVER_SCRIPT = ' + json.dumps(source) + ';\n\n'
    + 'export const SERVER_SCRIPT_SHA256 = ' + json.dumps(hashlib.sha256(source.encode()).hexdigest()) + ';\n'
    + '''
export function downloadServerScript(filename = 'can_ws_server.py'): void {
  const blob = new Blob([SERVER_SCRIPT], { type: 'text/x-python' });
  const link = document.createElement('a');
  link.download = filename;
  link.href = URL.createObjectURL(blob);
  link.click();
  URL.revokeObjectURL(link.href);
}
''')
print(f'Generated {target}')
